### ISSUE TITLE
{MOD CONFLICT} CRASH when brewing potions in a cauldron with Inspirations and Supplementaries installed

### ISSUE THREAD

**Issue by Cynix32** [omegaleo/mc-survessentials-mod#14]
**Describe the bug**
Inspirations mod adds a way of crafting potions using a cauldron. Brewing potions that way causes a crash when this mod is also installed
**To Reproduce**
1. put cauldron
2. make fire underneath using netherrack and flint&steel
3. fill the cauldron with water bucket, the cauldron should start boiling indicated with bubbles appearing on it.
4. throw a nether wart using q (default) or by right clicking the boiling cauldron with a nether wart
5. crash
**Expected behavior**
to not crash

**Desktop (please complete the following information):**
windows 10
forge 36.2.8
java 8
mc 1.16.5
Inspirations-1.16.5-1.2.3.38.jar
Mantle-1.16.5-1.6.127.jar
selene-1.16.5-1.8.1.jar
supplementaries-1.16.5-0.17.6.jar
survivalessentials-1.16.4-1.5.0.jar

**Comment by KnightMiner** [comment]
This is because [mc survessentials are returning null ItemStacks](https://github.com/omegaleo/mc-survessentials-mod/blob/main/src/main/java/pt/omegaleo/survivalessentials/brewing/VinegarRecipe.java#L40). That has been illegal since around 1.11, surprised you did not break the vanilla brewing stand with that.

**Comment by omegaleo** [comment]
@KnightMiner thank you for the help finding the issue, have been busy with work and didn't have time to take a look at it yet, already fixed it and will release a new version as soon as possible.
